
drop-if-inventory-is-full: true

##The GUI's are fully configurable.
gui:
  #This the main gui
  bank-gui:
    name: "&b&lDiamond Bank"
    size: 3
    button:
      close-button:
        item: "BARRIER"
        name: "&cClose"
        slot: 22
        lore:
          - "&fClick to close the bank"
          - "&r"
          - "&7Found what you are looking for?"
          - "&7Close the menu and move on :)"
      deposit-button:
        item: "base64:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzk3OGYzNWM2Mzg2MGQ2OTRmZWU0YWIzYzM2OTRmZGU0MDQ2Yzk2NmU0YzFiZjA2NjVmODg3NDhmOWY4MDI1In19fQ=="
        name: "&aDeposit"
        slot: 11
        lore:
          - "&fClick to open the menu"
          - "&r"
          - "&7This menu allows you to deposit money into the bank"
          - "&7Once deposited, you can later withdraw them later!"
      withdraw-button:
        item: "base64:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjNmMzM3ZDY5N2Y5ZDkxYWE4MTJlYjJjY2E2MmUzN2M2ZjZiNGEzOGIxMDMxYzFlNjJkMzVjNjgzZjU5ZDE5MiJ9fX0="
        name: "&eWithdraw"
        slot: 15
        lore:
          - "&fClick to open the menu"
          - "&r"
          - "&7You have diamonds on your bank, then withdraw it"
          - "&7Why waiting!"
      detail-button:
        item: "HOPPER"
        name: "&dAccount"
        slot: 26
        lore:
          - "&7Account ID &8» &f%player_uuid%"
          - "&7Account Balance &8» &f%balance%"
    filler:
      BLACK_STAINED_GLASS_PANE:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 17
        - 18
        - 19
        - 20
        - 21
        - 23
        - 24
        - 25
      GRAY_STAINED_GLASS_PANE:
        - 10
        - 12
        - 13
        - 14
        - 16
  deposit-gui:
    name: "&a&lDeposit Diamond"
    size: 5
    button:
      close-button:
        item: "BARRIER"
        name: "&cClose"
        slot: 40
        lore:
          - "&fClick to close the bank"
          - "&r"
          - "&7Found what you are looking for?"
          - "&7Close the menu and move on :)"
      deposit-button:
        item: "base64:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWI4ZmUxYzQ0YWNiZWViOTE4ZDM4YmM0MmQ1NTBiZWRkNWMzZGQwNDk4ODlmZDllZWVhMTE2MGFiOGI2YSJ9fX0="
        name: "&6Deposit your Diamond here!"
        slot: 22
        lore:
          - "&fDrop the amount of diamond"
          - "&fyou wish to deposit into the bank"
          - "&r"
          - "&7&lShift + LeftClick &r&7the diamond from "
          - "&7your hot-bar to deposit diamond"
      confirmation-yes:
        item: "base64:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWRmNzgyY2FlMmRkNTM5N2M0ODQ1ZmUxNGZiYTM2MTcyNDZkM2M0ZmE1NTAxMGQyMWJiNjIxNGJlMTM3YmQifX19"
        name: "&aFinalize Transaction"
        slot: 30
        lore:
          - "&fClick to deposit money in the bank"
          - "&r"
          - "&7This will finalize the transaction"
          - "&7and transfer the diamond into your account"
      confirmation-no:
        item: "base64:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZkZTNiZmNlMmQ4Y2I3MjRkZTg1NTZlNWVjMjFiN2YxNWY1ODQ2ODRhYjc4NTIxNGFkZDE2NGJlNzYyNGIifX19"
        name: "&cCancel Transaction"
        slot: 32
        lore:
          - "&fClick to cancel the deposit"
          - "&r"
          - "&7You doubt the amount?"
          - "&7You doubt whether its safe?"
          - "&7Well! you can rethink now!"
    filler:
      BLACK_STAINED_GLASS_PANE:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 18
        - 27
        - 36
        - 37
        - 38
        - 39
        - 41
        - 42
        - 43
        - 44
        - 35
        - 26
        - 17